NULL_NUCLEOTIDES = set(("N"))
NULL_NUCLEOTIDES_CHAR = "".join(NULL_NUCLEOTIDES)
REAL_NUCLEOTIDES = set(("C", "G", "A", "T"))
REAL_NUCLEOTIDES_CHARS = "".join(REAL_NUCLEOTIDES)
NUCLEOTIDES = REAL_NUCLEOTIDES.union(NULL_NUCLEOTIDES)
NUCLEOTIDES_CHARS = "".join(NUCLEOTIDES)

PHRED33_SCORES = {
    char: ord(char)
    for char in r"`1234567890-=qwertyuiop[]\asdfghjkl;'zxcvbnm,./~!@#$%^&*()_+QWERTYUIOP{}|ASDFGHJKL:\"ZXCVBNM<>?"
}
